image: python:3.9

stages:
    - install
    - test

install:
    before_script:
        - pip install pipenv
    script:
        - pip install pipenv
        - pip install -r requirements.txt

test:
    script:
        - python app/test/testServer.py
        - pipenv run test
