name: Python tests

on: push

# on:
#     push:
#         paths:
#             - "**.py"
#     pull_request:
#         paths:
#             - "**.py"

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
            - name: Installation de pipenv
              run: pip install pipenv
            - name: Installation des dépendances
              run: sudo apt-get install libmariadb3 libmariadb-dev -y
            - name: Création de l'environnement virtuel
              run: python3 -m venv .venv && source .venv/bin/activate
            - name: Installe les dépendances
              run: pip install -r requirements.txt

    test:
        runs-on: ubuntu-latest
        needs: install
        env:
            MODBUS_PORT: 5001
        steps:
            - uses: actions/checkout@v4
            - name: Lancement des tests
              run: python3 app/test/modbusclient/test.py
