name: Python tests
on:
    push:
        paths:
            - "**.py"
    pull_request:
        paths:
            - "**.py"

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Installation des dépendances
              run: sudo apt-get install libmariadb3 libmariadb-dev mariadb-server -y

            - name: Installation de pip et pipenv
              run: |
                  cd app
                  pipenv install
                  pipenv shell

            - name: Importe le schéma et les données de la BDD
              run: |
                  sudo mariadb < app/db/schema.sql
                  sudo mariadb < app/db/data.sql

            - name: Lancement des tests
              run: pipenv run test
